### PR TITLE
added files to be ignored during export

### PR DESCRIPTION
**Pull request by gabbydgab**
Additional files to be ignored during export:

- .docheader                                                                                                                                        
- CONDUCT.md                                                                              
- CONTRIBUTING.md
- README.md
- CHANGELOG.md

### CODE REVIEW

**Comment by Ocramius** [comment]
@gabbydgab can you rebase? I changed the target to `develop` on purpose.

**Comment by gabbydgab** [comment]
@Ocramius updated from upstream develop

**Comment by Ocramius** [comment]
Eh, no, that's a merge :-\

**Comment by gabbydgab** [comment]
@Ocramius sorry about that.. fixed rebase.. thanks

**Comment by geerteltink** [comment]
Why excluding important documents (CONDUCT, CONTRIBUTING, README, CHANGELOG) from tarballs?

Same in zendframework/zend-expressive-zendrouter#17

**Comment by gabbydgab** [comment]
@xtreamwayz

For consumer - may be irrelevant (except for change logs; if affected by X.Y.Z release)
For contributor - needed as guide.

If they experience BC breaks/bugs during updates, most of them look at the package repository and not in the vendor folder.

IMO, it will be much effective if release information will be added on composer.json  similar to [suggestions](https://getcomposer.org/doc/04-schema.md#suggest) because it explicitly explains the updated version of the dependency - maybe new composer feature? :thinking: 

```
"changes": {
    "added": ["new features"],
    "deprecated": ["notices"],
    "removed": ["removed"],
    "fixes": ["bc fixes or not"]
}
```



Thoughts?

**Comment by geerteltink** [comment]
Have you seen some of the changelogs? Besides issues with formatting, I don't think you want all that info in composer.json.

**Comment by gabbydgab** [comment]
Yes, but probably will just add a summary link pointing to those non-critical impacts. ONLY critical impacts like BC breaks will be added, others will be a summary link.

**Comment by weierophinney** [comment]
I'll merge, but with the following changes to no longer exclude the following files within `.gitattributes`:

- `CHANGELOG.md`
- `README.md`

These are user-facing files, and contain information that users may want/need to reference. While they may end up going to the repository website, this puts information at their fingertips immediately, and without requiring a network connection.

**Comment by weierophinney** [comment]
Thanks, @gabbydgab

**Pull request merged**
